#    Sheffield Type 2 Diabetes Treatment Model version 4.0: with the GLoW Trial health economic analysis implemented.
#    Copyright (C) 2023 Pidd, Pollard, Breeze, Bates, Thomas, Mueller, Ahern, Griffin, Brennan

#    This program is free software; you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation; either version 2 of the License, or
#    (at your option) any later version.

#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.

#    You should have received a copy of the GNU General Public License along
#    with this program; if not, write to the Free Software Foundation, Inc.,
#    51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.

#    Contact person: Katharine Pidd, Email: k.pidd@sheffield.ac.uk, 
#    Address: Regent Court, 30 Regent Court, Sheffield, United Kingdom, S1 4DA
####'This function runs the model for a given set of patients and parameters
####'@param population_, is the population matrix
####'@param parameters_, is one row of the parameters matrix
####'@param endtime_, is the number of years to run the simulation for
####'@param GlobalVars_, is the matrix giving the global variables
####'@param random_numbs_, is an array of common random numbers giving a random number
####'@param LifeTables_, is a dataframe containing life table information in formate
####'that can easily be matched to the population matrix
####'draw for each patient in each year for every event in which a random number 
####'is required 
####'@param SOUR_ is the number of the second order uncetainy run (PSA run)
####'@return results, is the results matrix
run_model <- function(population_, 
                      parameters_, 
                                  endtime_, 
                                  treatment_, 
                                  GlobalVars_,
                                  random_numbers_,
                                  LifeTables_){
  #see if the model run is deterministic
  #if it is run the model on the mean parameter values
  if(GlobalVars_["run_psa","Value"]==F){
    
    modelresults <- run_simulation(population_, 
                                   parameters_, 
                                     endtime_, 
                                     treatment_, 
                                     GlobalVars_,
                                     random_numbers_,
                                     LifeTables_,
                                     1)
  }else{#otherwise the model is PSA
    PSAiterations <- 2:(as.numeric(GlobalVars_["psa_count","Value"])+1)
    
    
    #set up parrallel processing
    #these are the additional global variables that need to be set for parrallel
    #processing functions
    numCores <- detectCores()-1
    numCores <- min (numCores, as.numeric(GlobalVars["Number of cores", "Value"]))
    cl <- makeCluster(numCores)
    #Set a random number seed for parallel processing
    clusterEvalQ(cl, set.seed(1))
    
    #Set up the cluster processing and push all objects in the global enviroment 
    #to all the clustes
    registerDoParallel(cl)
    clusterExport(cl, ls(envir = .GlobalEnv))
    modelresults <- parLapply(cl = cl,
                           PSAiterations, 
                           run_simulation,
                           population_ = population_,
                           parameters_ = parameters_,
                           endtime_ = endtime_,
                           treatment_ = treatment_, 
                           GlobalVars_ = GlobalVars_, 
                           random_numbs_ = random_numbers_,
                           LifeTables_ = LifeTables_)
    stopCluster(cl)
    
    if(GlobalVars["Results_output", "Value"] == "Summary"){
      modelresults <- matrix(unlist(modelresults), ncol=426, byrow=T)
    colnames(modelresults) <- c("Life Years", 
                                "Discounted Life Years",
                                "QALYs", 
                                "Discounted QALYs", 
                                "Costs",
                                "Discounted Costs",
                                "1 year death",
                                "1 year alive year end",
                                "1 year 1st MIs",
                                "1 year 2nd MIs",
                                "1 year 1st Strokes",
                                "1 year 2nd Strokes",
                                "1 year CHF",
                                "1 year IHD",
                                "1 year blindness",
                                "1 year ulcers",
                                "1 year 1st amputations",
                                "1 year 2nd amputations",
                                "1 year renal failures",
                                "1 year PVD",
                                "1 year MMALB",
                                "1 year Atrial Fibriliation",
                                "1 year breast cancer",
                                "1 year colorectal cancer",
                                "1 year depression",
                                "1 year oestoarthritis",
                                "2 year death",
                                "2 year alive year end",
                                "2 year 1st MIs",
                                "2 year 2nd MIs",
                                "2 year 1st Strokes",
                                "2 year 2nd Strokes",
                                "2 year CHF",
                                "2 year IHD",
                                "2 year blindness",
                                "2 year ulcers",
                                "2 year 1st amputations",
                                "2 year 2nd amputations",
                                "2 year renal failures",
                                "2 year PVD",
                                "2 year MMALB",
                                "2 year Atrial Fibriliation",
                                "2 year breast cancer",
                                "2 year colorectal cancer",
                                "2 year depression",
                                "2 year oestoarthritis",
                                "3 year death",
                                "3 year alive year end",
                                "3 year 1st MIs",
                                "3 year 2nd MIs",
                                "3 year 1st Strokes",
                                "3 year 2nd Strokes",
                                "3 year CHF",
                                "3 year IHD",
                                "3 year blindness",
                                "3 year ulcers",
                                "3 year 1st amputations",
                                "3 year 2nd amputations",
                                "3 year renal failures",
                                "3 year PVD",
                                "3 year MMALB",
                                "3 year Atrial Fibriliation",
                                "3 year breast cancer",
                                "3 year colorectal cancer",
                                "3 year depression",
                                "3 year oestoarthritis",
                                "4 year death",
                                "4 year alive year end",
                                "4 year 1st MIs",
                                "4 year 2nd MIs",
                                "4 year 1st Strokes",
                                "4 year 2nd Strokes",
                                "4 year CHF",
                                "4 year IHD",
                                "4 year blindness",
                                "4 year ulcers",
                                "4 year 1st amputations",
                                "4 year 2nd amputations",
                                "4 year renal failures",
                                "4 year PVD",
                                "4 year MMALB",
                                "4 year Atrial Fibriliation",
                                "4 year breast cancer",
                                "4 year colorectal cancer",
                                "4 year depression",
                                "4 year oestoarthritis",
                                "5 year death",
                                "5 year alive year end",
                                "5 year 1st MIs",
                                "5 year 2nd MIs",
                                "5 year 1st Strokes",
                                "5 year 2nd Strokes",
                                "5 year CHF",
                                "5 year IHD",
                                "5 year blindness",
                                "5 year ulcers",
                                "5 year 1st amputations",
                                "5 year 2nd amputations",
                                "5 year renal failures",
                                "5 year PVD",
                                "5 year MMALB",
                                "5 year Atrial Fibriliation",
                                "5 year breast cancer",
                                "5 year colorectal cancer",
                                "5 year depression",
                                "5 year oestoarthritis",
                                "6 year death",
                                "6 year alive year end",
                                "6 year 1st MIs",
                                "6 year 2nd MIs",
                                "6 year 1st Strokes",
                                "6 year 2nd Strokes",
                                "6 year CHF",
                                "6 year IHD",
                                "6 year blindness",
                                "6 year ulcers",
                                "6 year 1st amputations",
                                "6 year 2nd amputations",
                                "6 year renal failures",
                                "6 year PVD",
                                "6 year MMALB",
                                "6 year Atrial Fibriliation",
                                "6 year breast cancer",
                                "6 year colorectal cancer",
                                "6 year depression",
                                "6 year oestoarthritis",
                                "7 year death",
                                "7 year alive year end",
                                "7 year 1st MIs",
                                "7 year 2nd MIs",
                                "7 year 1st Strokes",
                                "7 year 2nd Strokes",
                                "7 year CHF",
                                "7 year IHD",
                                "7 year blindness",
                                "7 year ulcers",
                                "7 year 1st amputations",
                                "7 year 2nd amputations",
                                "7 year renal failures",
                                "7 year PVD",
                                "7 year MMALB",
                                "7 year Atrial Fibriliation",
                                "7 year breast cancer",
                                "7 year colorectal cancer",
                                "7 year depression",
                                "7 year oestoarthritis",
                                "8 year death",
                                "8 year alive year end",
                                "8 year 1st MIs",
                                "8 year 2nd MIs",
                                "8 year 1st Strokes",
                                "8 year 2nd Strokes",
                                "8 year CHF",
                                "8 year IHD",
                                "8 year blindness",
                                "8 year ulcers",
                                "8 year 1st amputations",
                                "8 year 2nd amputations",
                                "8 year renal failures",
                                "8 year PVD",
                                "8 year MMALB",
                                "8 year Atrial Fibriliation",
                                "8 year breast cancer",
                                "8 year colorectal cancer",
                                "8 year depression",
                                "8 year oestoarthritis",
                                "9 year death",
                                "9 year alive year end",
                                "9 year 1st MIs",
                                "9 year 2nd MIs",
                                "9 year 1st Strokes",
                                "9 year 2nd Strokes",
                                "9 year CHF",
                                "9 year IHD",
                                "9 year blindness",
                                "9 year ulcers",
                                "9 year 1st amputations",
                                "9 year 2nd amputations",
                                "9 year renal failures",
                                "9 year PVD",
                                "9 year MMALB",
                                "9 year Atrial Fibriliation",
                                "9 year breast cancer",
                                "9 year colorectal cancer",
                                "9 year depression",
                                "9 year oestoarthritis",
                                "10 year death",
                                "10 year alive year end",
                                "10 year 1st MIs",
                                "10 year 2nd MIs",
                                "10 year 1st Strokes",
                                "10 year 2nd Strokes",
                                "10 year CHF",
                                "10 year IHD",
                                "10 year blindness",
                                "10 year ulcers",
                                "10 year 1st amputations",
                                "10 year 2nd amputations",
                                "10 year renal failures",
                                "10 year PVD",
                                "10 year MMALB",
                                "10 year Atrial Fibriliation",
                                "10 year breast cancer",
                                "10 year colorectal cancer",
                                "10 year depression",
                                "10 year oestoarthritis",
                                "11 year death",
                                "11 year alive year end",
                                "11 year 1st MIs",
                                "11 year 2nd MIs",
                                "11 year 1st Strokes",
                                "11 year 2nd Strokes",
                                "11 year CHF",
                                "11 year IHD",
                                "11 year blindness",
                                "11 year ulcers",
                                "11 year 1st amputations",
                                "11 year 2nd amputations",
                                "11 year renal failures",
                                "11 year PVD",
                                "11 year MMALB",
                                "11 year Atrial Fibriliation",
                                "11 year breast cancer",
                                "11 year colorectal cancer",
                                "11 year depression",
                                "11 year oestoarthritis",
                                "12 year death",
                                "12 year alive year end",
                                "12 year 1st MIs",
                                "12 year 2nd MIs",
                                "12 year 1st Strokes",
                                "12 year 2nd Strokes",
                                "12 year CHF",
                                "12 year IHD",
                                "12 year blindness",
                                "12 year ulcers",
                                "12 year 1st amputations",
                                "12 year 2nd amputations",
                                "12 year renal failures",
                                "12 year PVD",
                                "12 year MMALB",
                                "12 year Atrial Fibriliation",
                                "12 year breast cancer",
                                "12 year colorectal cancer",
                                "12 year depression",
                                "12 year oestoarthritis",
                                "13 year death",
                                "13 year alive year end",
                                "13 year 1st MIs",
                                "13 year 2nd MIs",
                                "13 year 1st Strokes",
                                "13 year 2nd Strokes",
                                "13 year CHF",
                                "13 year IHD",
                                "13 year blindness",
                                "13 year ulcers",
                                "13 year 1st amputations",
                                "13 year 2nd amputations",
                                "13 year renal failures",
                                "13 year PVD",
                                "13 year MMALB",
                                "13 year Atrial Fibriliation",
                                "13 year breast cancer",
                                "13 year colorectal cancer",
                                "13 year depression",
                                "13 year oestoarthritis",
                                "14 year death",
                                "14 year alive year end",
                                "14 year 1st MIs",
                                "14 year 2nd MIs",
                                "14 year 1st Strokes",
                                "14 year 2nd Strokes",
                                "14 year CHF",
                                "14 year IHD",
                                "14 year blindness",
                                "14 year ulcers",
                                "14 year 1st amputations",
                                "14 year 2nd amputations",
                                "14 year renal failures",
                                "14 year PVD",
                                "14 year MMALB",
                                "14 year Atrial Fibriliation",
                                "14 year breast cancer",
                                "14 year colorectal cancer",
                                "14 year depression",
                                "14 year oestoarthritis",
                                "15 year death",
                                "15 year alive year end",
                                "15 year 1st MIs",
                                "15 year 2nd MIs",
                                "15 year 1st Strokes",
                                "15 year 2nd Strokes",
                                "15 year CHF",
                                "15 year IHD",
                                "15 year blindness",
                                "15 year ulcers",
                                "15 year 1st amputations",
                                "15 year 2nd amputations",
                                "15 year renal failures",
                                "15 year PVD",
                                "15 year MMALB",
                                "15 year Atrial Fibriliation",
                                "15 year breast cancer",
                                "15 year colorectal cancer",
                                "15 year depression",
                                "15 year oestoarthritis",
                                "16 year death",
                                "16 year alive year end",
                                "16 year 1st MIs",
                                "16 year 2nd MIs",
                                "16 year 1st Strokes",
                                "16 year 2nd Strokes",
                                "16 year CHF",
                                "16 year IHD",
                                "16 year blindness",
                                "16 year ulcers",
                                "16 year 1st amputations",
                                "16 year 2nd amputations",
                                "16 year renal failures",
                                "16 year PVD",
                                "16 year MMALB",
                                "16 year Atrial Fibriliation",
                                "16 year breast cancer",
                                "16 year colorectal cancer",
                                "16 year depression",
                                "16 year oestoarthritis",
                                "17 year death",
                                "17 year alive year end",
                                "17 year 1st MIs",
                                "17 year 2nd MIs",
                                "17 year 1st Strokes",
                                "17 year 2nd Strokes",
                                "17 year CHF",
                                "17 year IHD",
                                "17 year blindness",
                                "17 year ulcers",
                                "17 year 1st amputations",
                                "17 year 2nd amputations",
                                "17 year renal failures",
                                "17 year PVD",
                                "17 year MMALB",
                                "17 year Atrial Fibriliation",
                                "17 year breast cancer",
                                "17 year colorectal cancer",
                                "17 year depression",
                                "17 year oestoarthritis",
                                "18 year death",
                                "18 year alive year end",
                                "18 year 1st MIs",
                                "18 year 2nd MIs",
                                "18 year 1st Strokes",
                                "18 year 2nd Strokes",
                                "18 year CHF",
                                "18 year IHD",
                                "18 year blindness",
                                "18 year ulcers",
                                "18 year 1st amputations",
                                "18 year 2nd amputations",
                                "18 year renal failures",
                                "18 year PVD",
                                "18 year MMALB",
                                "18 year Atrial Fibriliation",
                                "18 year breast cancer",
                                "18 year colorectal cancer",
                                "18 year depression",
                                "18 year oestoarthritis",
                                "19 year death",
                                "19 year alive year end",
                                "19 year 1st MIs",
                                "19 year 2nd MIs",
                                "19 year 1st Strokes",
                                "19 year 2nd Strokes",
                                "19 year CHF",
                                "19 year IHD",
                                "19 year blindness",
                                "19 year ulcers",
                                "19 year 1st amputations",
                                "19 year 2nd amputations",
                                "19 year renal failures",
                                "19 year PVD",
                                "19 year MMALB",
                                "19 year Atrial Fibriliation",
                                "19 year breast cancer",
                                "19 year colorectal cancer",
                                "19 year depression",
                                "19 year oestoarthritis",
                                "20 year death",
                                "20 year alive year end",
                                "20 year 1st MIs",
                                "20 year 2nd MIs",
                                "20 year 1st Strokes",
                                "20 year 2nd Strokes",
                                "20 year CHF",
                                "20 year IHD",
                                "20 year blindness",
                                "20 year ulcers",
                                "20 year 1st amputations",
                                "20 year 2nd amputations",
                                "20 year renal failures",
                                "20 year PVD",
                                "20 year MMALB",
                                "20 year Atrial Fibriliation",
                                "20 year breast cancer",
                                "20 year colorectal cancer",
                                "20 year depression",
                                "20 year oestoarthritis",
                                "21 year death",
                                "21 year alive year end",
                                "21 year 1st MIs",
                                "21 year 2nd MIs",
                                "21 year 1st Strokes",
                                "21 year 2nd Strokes",
                                "21 year CHF",
                                "21 year IHD",
                                "21 year blindness",
                                "21 year ulcers",
                                "21 year 1st amputations",
                                "21 year 2nd amputations",
                                "21 year renal failures",
                                "21 year PVD",
                                "21 year MMALB",
                                "21 year Atrial Fibriliation",
                                "21 year breast cancer",
                                "21 year colorectal cancer",
                                "21 year depression",
                                "21 year oestoarthritis")
    }
  }
  return(modelresults)
}
